WORDS = [
    # Animals
    "elephant", "giraffe", "penguin", "dolphin", "butterfly", "crocodile",
    "rhinoceros", "chimpanzee", "kangaroo", "flamingo", "chameleon", "porcupine",
    "wolverine", "albatross", "armadillo", "salamander", "orangutan", "mongoose",
    "platypus", "pelican", "walrus", "narwhal", "cheetah", "leopard",
    "jaguar", "panther", "cougar", "lynx", "badger", "weasel",
    "ferret", "meerkat", "capybara", "tapir", "manatee", "dugong",
    "stingray", "barracuda", "piranha", "jellyfish", "seahorse", "octopus",
    "squid", "lobster", "crayfish", "scorpion", "tarantula", "centipede",
    "millipede", "dragonfly", "grasshopper", "cricket", "firefly", "ladybug",
    "praying mantis", "caterpillar", "cockatoo", "macaw", "toucan", "hornbill",
    "kingfisher", "hummingbird", "woodpecker", "roadrunner", "ostrich", "cassowary",
    "peacock", "pheasant", "quail", "partridge", "ibis", "stork",
    "egret", "heron", "cormorant", "gannet", "puffin", "razorbill",
    "guillemot", "skua", "frigatebird", "booby", "tropicbird", "petrel",
    # Technology
    "algorithm", "database", "network", "interface", "keyboard", "software",
    "hardware", "firmware", "internet", "bandwidth", "protocol", "encryption",
    "javascript", "python", "compiler", "debugger", "repository", "framework",
    "container", "microservice", "kubernetes", "terraform", "ansible", "docker",
    "blockchain", "cryptocurrency", "artificial", "intelligence", "machine", "learning",
    "neural", "network", "transistor", "semiconductor", "processor", "motherboard",
    "graphics", "monitor", "peripheral", "touchscreen", "bluetooth", "wireless",
    "satellite", "broadband", "fibre", "router", "firewall", "proxy",
    "malware", "phishing", "ransomware", "cybersecurity", "penetration", "vulnerability",
    "authentication", "authorization", "cryptography", "certificate", "tokenization",
    "virtualisation", "hypervisor", "cloudcomputing", "serverless", "devops",
    "agile", "scrum", "kanban", "retrospective", "deployment", "pipeline",
    "refactoring", "abstraction", "inheritance", "polymorphism", "encapsulation",
    # Nature & Geography
    "mountains", "waterfall", "volcano", "glacier", "canyon", "peninsula",
    "archipelago", "savanna", "tundra", "permafrost", "rainforest", "mangrove",
    "estuary", "lagoon", "atoll", "plateau", "mesa", "butte",
    "stalactite", "stalagmite", "geyser", "fumarole", "caldera", "magma",
    "tsunami", "hurricane", "typhoon", "cyclone", "tornado", "blizzard",
    "avalanche", "mudslide", "earthquake", "aftershock", "tremor", "fault",
    "monsoon", "drought", "flooding", "erosion", "sedimentation", "weathering",
    "photosynthesis", "chlorophyll", "pollination", "germination", "decomposition",
    "symbiosis", "ecosystem", "biosphere", "atmosphere", "stratosphere", "ionosphere",
    # Food & Drink
    "chocolate", "strawberry", "pineapple", "blueberry", "raspberry", "blackberry",
    "pomegranate", "persimmon", "tangerine", "clementine", "grapefruit", "avocado",
    "artichoke", "asparagus", "aubergine", "courgette", "broccoli", "cauliflower",
    "coriander", "cardamom", "turmeric", "cinnamon", "nutmeg", "saffron",
    "mozzarella", "parmesan", "gorgonzola", "camembert", "brie", "gruyere",
    "croissant", "baguette", "sourdough", "brioche", "focaccia", "ciabatta",
    "prosciutto", "salami", "chorizo", "pancetta", "pepperoni", "pastrami",
    "sauerkraut", "kimchi", "hummus", "tzatziki", "guacamole", "salsa",
    "espresso", "cappuccino", "macchiato", "latte", "americano", "frappuccino",
    "kombucha", "kefir", "smoothie", "milkshake", "lemonade", "sparkling",
    # Music & Arts
    "guitar", "trumpet", "violin", "saxophone", "percussion", "clarinet",
    "trombone", "flugelhorn", "harpsichord", "xylophone", "marimba", "theremin",
    "symphony", "concerto", "sonata", "overture", "serenade", "nocturne",
    "baroque", "classical", "romantic", "impressionist", "expressionist", "surrealist",
    "sculpture", "installation", "lithograph", "engraving", "watercolour", "fresco",
    "calligraphy", "typography", "illustration", "animation", "cinematography",
    "choreography", "improvisation", "composition", "arrangement", "harmony",
    "counterpoint", "modulation", "cadence", "arpeggio", "pizzicato", "vibrato",
    # Buildings & Places
    "hospital", "library", "cathedral", "stadium", "museum", "aquarium",
    "planetarium", "observatory", "laboratory", "auditorium", "amphitheatre",
    "parliament", "courthouse", "embassy", "consulate", "barracks", "fortress",
    "lighthouse", "windmill", "aqueduct", "colosseum", "parthenon", "pantheon",
    "mausoleum", "cenotaph", "obelisk", "minaret", "pagoda", "ziggurat",
    "skyscraper", "penthouse", "bungalow", "townhouse", "apartment", "mansion",
    "bungalow", "chalet", "cottage", "farmhouse", "greenhouse", "orangery",
    # Science & Medicine
    "telescope", "microscope", "thermometer", "calculator", "compass", "barometer",
    "spectroscope", "oscilloscope", "centrifuge", "chromatography", "electrolysis",
    "photosynthesis", "mitochondria", "chromosome", "metabolism", "antibody",
    "vaccine", "antibiotic", "analgesic", "anaesthetic", "diagnosis", "prognosis",
    "pathology", "radiology", "cardiology", "neurology", "oncology", "dermatology",
    "psychiatry", "psychology", "physiology", "anatomy", "biochemistry", "genetics",
    "evolution", "mutation", "selection", "adaptation", "extinction", "biodiversity",
    "quantum", "relativity", "gravity", "magnetism", "electricity", "thermodynamics",
    "entropy", "momentum", "velocity", "acceleration", "frequency", "wavelength",
    # History & Culture
    "philosophy", "democracy", "revolution", "civilization", "knowledge", "enlightenment",
    "renaissance", "reformation", "inquisition", "crusade", "conquest", "colonialism",
    "imperialism", "nationalism", "socialism", "capitalism", "communism", "anarchism",
    "feudalism", "mercantilism", "industrialisation", "urbanisation", "globalisation",
    "archaeology", "anthropology", "ethnography", "linguistics", "semiotics",
    "mythology", "folklore", "superstition", "ritual", "ceremony", "tradition",
    "parliament", "monarchy", "republic", "federation", "confederation", "sovereignty",
    "constitution", "amendment", "legislation", "judiciary", "executive", "electoral",
    # Sports & Recreation
    "basketball", "volleyball", "badminton", "wrestling", "gymnastics", "athletics",
    "triathlon", "decathlon", "pentathlon", "equestrian", "fencing", "archery",
    "bobsleigh", "luge", "skeleton", "biathlon", "slalom", "freestyle",
    "skateboarding", "surfing", "snowboarding", "paragliding", "skydiving", "bungee",
    "orienteering", "mountaineering", "abseiling", "kayaking", "rafting", "windsurfing",
    "snorkelling", "scuba", "freediving", "spearfishing", "flyboarding",
    # Adventure & Travel
    "adventure", "mystery", "treasure", "journey", "courage", "expedition",
    "exploration", "navigation", "cartography", "topography", "surveying",
    "backpacking", "hitchhiking", "pilgrimage", "excursion", "itinerary",
    "passport", "customs", "immigration", "quarantine", "departure", "arrival",
    "turbulence", "altitude", "longitude", "latitude", "meridian", "equator",
    # Abstract & Concepts
    "ambiguity", "paradox", "contradiction", "abstraction", "metaphor", "allegory",
    "symbolism", "archetype", "narrative", "protagonist", "antagonist", "dialogue",
    "soliloquy", "monologue", "rhetoric", "eloquence", "persuasion", "argument",
    "hypothesis", "theorem", "axiom", "postulate", "inference", "deduction",
    "induction", "analogy", "syllogism", "empiricism", "rationalism", "skepticism",
    "consciousness", "perception", "cognition", "intuition", "imagination", "creativity",
    "motivation", "ambition", "perseverance", "resilience", "integrity", "compassion",
    "empathy", "solidarity", "collaboration", "innovation", "sustainability",
    # Clothing & Fashion
    "cardigan", "cashmere", "chiffon", "corduroy", "dungarees", "gabardine",
    "herringbone", "linen", "mohair", "organza", "paisley", "pinstripe",
    "tartan", "tweed", "velvet", "brocade", "damask", "jacquard",
    "leggings", "trousers", "waistcoat", "cummerbund", "cravat", "turtleneck",
    "trenchcoat", "mackintosh", "windbreaker", "dungaree", "overalls", "jumpsuit",
    "stiletto", "loafers", "moccasin", "espadrille", "sandals", "galoshes",
    # Vehicles & Transport
    "locomotive", "submarine", "helicopter", "catamaran", "hovercraft", "gondola",
    "rickshaw", "palanquin", "stagecoach", "carriage", "chariot", "sleigh",
    "zeppelin", "airship", "glider", "ultralight", "paramotor", "microlight",
    "tanker", "freighter", "destroyer", "battleship", "aircraft", "carrier",
    "bulldozer", "excavator", "forklift", "harvester", "combine", "tractor",
    "ambulance", "firetruck", "limousine", "convertible", "minivan", "pickup",
    # Occupations
    "archaeologist", "astronomer", "biochemist", "cartographer", "choreographer",
    "cryptographer", "dermatologist", "diplomat", "ecologist", "entomologist",
    "epidemiologist", "etymologist", "geographer", "geologist", "herpetologist",
    "immunologist", "lexicographer", "meteorologist", "microbiologist", "neurologist",
    "ornithologist", "palaeontologist", "pharmacologist", "physiotherapist", "radiologist",
    "seismologist", "toxicologist", "virologist", "zoologist", "sommelier",
    "confectioner", "patissier", "sommelier", "vintner", "distiller", "brewer",
    # Emotions & Psychology
    "melancholy", "nostalgia", "euphoria", "anxiety", "paranoia", "apathy",
    "schadenfreude", "wanderlust", "serendipity", "epiphany", "catharsis",
    "adrenaline", "serotonin", "dopamine", "oxytocin", "cortisol", "melatonin",
    "introvert", "extrovert", "ambivert", "narcissism", "altruism", "stoicism",
    "hedonism", "nihilism", "existentialism", "pragmatism", "idealism", "realism",
    # Geology & Minerals
    "obsidian", "basalt", "granite", "limestone", "sandstone", "quartzite",
    "amethyst", "sapphire", "emerald", "turquoise", "topaz", "garnet",
    "malachite", "lapis", "lazuli", "alabaster", "onyx", "jasper",
    "stalactite", "dolomite", "feldspar", "mica", "pumice", "flint",
    "magnesium", "aluminium", "titanium", "platinum", "palladium", "rhodium",
    # Literature & Writing
    "bibliography", "biography", "autobiography", "anthology", "encyclopedia",
    "dictionary", "thesaurus", "periodical", "manuscript", "parchment", "papyrus",
    "prologue", "epilogue", "preface", "foreword", "appendix", "glossary",
    "onomatopoeia", "alliteration", "assonance", "consonance", "enjambment",
    "iambic", "pentameter", "trochee", "spondee", "dactyl", "anapest",
    "haiku", "sonnet", "ballad", "limerick", "elegy", "ode",
    # Mathematics
    "arithmetic", "geometry", "calculus", "trigonometry", "statistics", "probability",
    "differential", "integral", "quadratic", "polynomial", "logarithm", "exponential",
    "fibonacci", "factorial", "permutation", "combination", "determinant", "matrix",
    "topology", "algebra", "boolean", "hexadecimal", "binary", "octal",
    "asymptote", "parabola", "hyperbola", "ellipse", "tangent", "cosine",
    # Space & Astronomy
    "supernova", "nebula", "quasar", "pulsar", "magnetar", "blackhole",
    "asteroid", "meteorite", "comet", "constellation", "equinox", "solstice",
    "aphelion", "perihelion", "apogee", "perigee", "parallax", "redshift",
    "photosphere", "chromosphere", "heliosphere", "magnetosphere", "exoplanet",
    "cosmology", "astrophysics", "spectroscopy", "astrometry", "interferometry",
    # Languages & Linguistics
    "onomatopoeia", "homophone", "homonym", "synonym", "antonym", "palindrome",
    "portmanteau", "oxymoron", "euphemism", "pleonasm", "tautology", "solecism",
    "bilingual", "multilingual", "polyglot", "dialect", "vernacular", "pidgin",
    "creole", "morpheme", "phoneme", "syllable", "diphthong", "consonant",
    "declension", "conjugation", "subjunctive", "participle", "infinitive", "gerund",
    # Architecture & Design
    "cantilever", "buttress", "balustrade", "cornice", "pediment", "pilaster",
    "colonnade", "portico", "atrium", "clerestory", "battlement", "parapet",
    "turret", "gargoyle", "finial", "pinnacle", "spire", "steeple",
    "architrave", "entablature", "frieze", "metope", "triglyph", "volute",
    "rotunda", "transept", "nave", "apse", "narthex", "ambulatory",
    # Cooking & Kitchen
    "blanching", "braising", "caramelise", "deglaze", "emulsify", "flambé",
    "julienne", "marinate", "poaching", "reduction", "sauté", "tempering",
    "colander", "mandoline", "ramekin", "tagine", "terrine", "casserole",
    "whetstone", "spatula", "whisk", "ladle", "skimmer", "tongs",
    "béchamel", "hollandaise", "velouté", "vinaigrette", "remoulade", "aioli",
    # Hobbies & Crafts
    "embroidery", "macramé", "origami", "decoupage", "mosaics", "marquetry",
    "woodcarving", "pyrography", "leatherwork", "bookbinding", "calligraphy", "etching",
    "glassblowing", "ceramics", "pottery", "sculpting", "weaving", "knitting",
    "crocheting", "quilting", "tapestry", "beadwork", "jewellery", "watchmaking",
    "taxidermy", "falconry", "beekeeping", "lepidoptery", "philately", "numismatics",
    # Health & Fitness
    "cardiovascular", "metabolism", "flexibility", "endurance", "hydration", "nutrition",
    "meditation", "mindfulness", "acupuncture", "osteopathy", "chiropractic", "physiotherapy",
    "rehabilitation", "convalescence", "immunisation", "inoculation", "quarantine", "pandemic",
    # Weather & Climate
    "barometric", "precipitation", "evaporation", "condensation", "sublimation", "humidity",
    "inversion", "convection", "radiation", "albedo", "greenhouse", "deforestation",
    "biodegradable", "composting", "recycling", "renewable", "photovoltaic", "geothermal",
    # Business & Economics
    "entrepreneur", "corporation", "franchise", "subsidiary", "conglomerate", "monopoly",
    "oligopoly", "inflation", "deflation", "stagflation", "recession", "depression",
    "portfolio", "dividend", "arbitrage", "derivative", "commodity", "liquidation",
    "bankruptcy", "insolvency", "amalgamation", "acquisition", "merger", "divestiture",
    # Government & Law
    "legislation", "jurisdiction", "precedent", "affidavit", "subpoena", "injunction",
    "plaintiff", "defendant", "prosecutor", "magistrate", "barrister", "solicitor",
    "extradition", "amnesty", "clemency", "litigation", "arbitration", "mediation",
]

# Deduplicate while preserving order
seen = set()
WORDS = [w for w in WORDS if not (w.upper() in seen or seen.add(w.upper()))]
